### ISSUE TITLE
Multi-line markdown cells erroneously become collapsable 

### ISSUE THREAD

**Issue by marius311** [aquirdTurtle/Collapsible_Headings#4]
First, a HUGE thank you for this, I've literally been waiting for this for maybe a year since switching away from notebook. Its so good to have this back! 

Second, a small bug I found I'll report here, basically looks like multi-line markdown cells erroneously become like a "heading" (and will collapse everything below them):

![image](https://user-images.githubusercontent.com/1510968/62647313-1b916800-b905-11e9-9da9-99a4d9d42f41.png)

This is with collapsible_headings v0.3.1 / JupyterLab 1.0.4.

**Comment by aquirdTurtle** [comment]
Hey, I was unable to cleanly reproduce this (actually, I can't get markdown to render a single letter per line in jupyterlab for some reason), but in v0.3.2 I fixed a perhaps related bug where old buttons weren't getting removed properly when heading cells were edited to be not headers. Perhaps this fixes what you were seeing, or perhaps you could show a different example?

**Comment by marius311** [comment]
Thanks, just checked out v0.3.2 and I unfortunately still see the bug. Here's a video:

![ocr](https://user-images.githubusercontent.com/1510968/62840030-d644a180-bc48-11e9-817e-c536d92882cf.gif)

More about my setup:
```
$ jupyter labextension list
JupyterLab v1.0.4
Known labextensions:
   app dir: /home/marius/.pyenv/versions/3.7.3/share/jupyter/lab
        @aquirdturtle/collapsible_headings v0.3.2  enabled  OK
        @jupyterlab/toc v1.0.1  enabled  OK
        jupyterlab-favorites v1.0.0  enabled  OK
        nbdime-jupyterlab v1.0.0  enabled  OK

   linked packages:
        @webio/webio: /home/marius/.julia/packages/WebIO/nNJPv/packages/webio

$ google-chrome --version
Google Chrome 76.0.3809.87 
```



Incidentally, in my video you can see another small bug I've discovered which is that if you click to expand/collapse really fast, you trigger the cell into edit mode.

**Comment by aquirdTurtle** [comment]
Gotcha, thanks. It was a bug associated with having an empty second line in the markdown cell. Should be fixed in v0.3.3, just released. 

The double click behavior is a little less related to the extension and is probably harder to improve here. For example, the same thing happens if you double-click on the input collapse button (as opposed to the header collapse button) or that left-side area of any non-header cell.

**Comment by marius311** [comment]
That did it, thank you!
